
<!DOCTYPE html>
<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <title>MessageAkoh - Aksi Cepat Tanggap - Lembaga kemanusiaan</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta name="author" content="Aksi Cepat Tanggap">
    <meta content="Aksi Cepat Tanggap" name="title">
    <meta content="Organisasi kemanusiaan global profesional berbasis kedermawanan dan kerelawanan masyarakat global" name="description">
    <meta content="Aksi Cepat Tanggap" name="keywords">
    <meta property="fb:pages" content="49951758518" />

    <meta property="og:title" content="" />
    <meta property="og:type" content="" />
    <meta property="og:url" content="" />
    <meta property="og:image" content="" />
    <meta property="og:image:secure_url" content="" />
    
    <link href="https://act.id/assets/images/ACT-icon 32-01.ico" rel=
    "shortcut icon">
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
<!--    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="layerslider/css/layerslider.css" rel="stylesheet" type="text/css">
    <link href="css/icons.css" rel="stylesheet">
    <link href="css/slick.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet" type="text/css">
    <link href="css/responsive.css" rel="stylesheet" type="text/css">
    <link href="css/colors/color.css" rel="stylesheet" title="color1" type= -->
    <link rel='stylesheet' type='text/css' href='https://act.id/themes/act_id/css/bootstrap.min.css' media='screen' />
<link rel='stylesheet' type='text/css' href='https://act.id/themes/act_id/css/icons.css' media='screen' />
<link rel='stylesheet' type='text/css' href='https://act.id/themes/act_id/css/slick.css' media='screen' />
<link rel='stylesheet' type='text/css' href='https://act.id/themes/act_id/css/style.css' media='screen' />
<link rel='stylesheet' type='text/css' href='https://act.id/themes/act_id/css/responsive.css' media='screen' />
<link rel='stylesheet' type='text/css' href='https://act.id/themes/act_id/css/colors/color.css' media='screen' />
<link rel='stylesheet' type='text/css' href='https://act.id/themes/act_id/css/bootstrap-datepicker3.min.css' media='screen' />
    
        
</head>
<body itemscope>
    <div id="fb-root"></div>
 

    <a href="https://act.id/donasi">
    <div class="btn-donate-mobile donasi-mbl">
        DONASI SEKARANG <!-- </div></a> <a href="https://act.id/relawan"> -->
    </div></a> <a target="_blank" href="https://relawan.id/daftar-relawan/">
    <div class="btn-donate-mobile relawan-mbl">
        JADI RELAWAN    </div></a>
    <div class="theme-layout">
        <header class="stick">
            <div class="topbar dark">
                <div class="container">
                     
                </div>
            </div>
                        <div class="menu">
                <div class="container">
                    <div class="logo">
                        <a href="https://act.id/" itemprop="url" title=""><img alt="" itemprop="image"
                        src="https://act.id/assets/images/logo.png"></a>
                    </div>
                    <nav>
                        <a class="theme-btn" href="https://act.id/donasi" itemprop="url" style=
                        "background:rgba(241,91,38,1);" title="">DONASI SEKARANG</a> <a target="_blank" class=
                        "theme-btn" href="https://relawan.id/daftar-relawan/" itemprop="url" style="background:#E2332E;"
                        title="">JADI RELAWAN</a>
                        <ul>
                            <li>
                                <a class="active-menu" href="https://act.id/" itemprop="url" title=
                                "">Ayo Bantu Sodara - Sodara Kita.</a>
                            </li>
                             
                            
                        </ul>
                    </nav>
                </div>
            </div>
                    </header>
      
        
<!--<div class="container"> Start of Main Container -->
        <section class="sec-slide">
            <div class="block gray no-padding">
                <div class="">
                    <div class="row">
                        <div class="col-md-12 column">
                            <div class="carousel slide" data-ride="carousel" id="myCarousel">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                                                        <li class="active" data-slide-to="0" data-target="#myCarousel"></li>
                                    <!-- <li data-slide-to="1" data-target="#myCarousel"></li>
                                    <li data-slide-to="2" data-target="#myCarousel"></li>
                                    <li data-slide-to="3" data-target="#myCarousel"></li> -->
                                                                        <li class="" data-slide-to="1" data-target="#myCarousel"></li>
                                    <!-- <li data-slide-to="1" data-target="#myCarousel"></li>
                                    <li data-slide-to="2" data-target="#myCarousel"></li>
                                    <li data-slide-to="3" data-target="#myCarousel"></li> -->
                                                                        <li class="" data-slide-to="2" data-target="#myCarousel"></li>
                                    <!-- <li data-slide-to="1" data-target="#myCarousel"></li>
                                    <li data-slide-to="2" data-target="#myCarousel"></li>
                                    <li data-slide-to="3" data-target="#myCarousel"></li> -->
                                                                        <li class="" data-slide-to="3" data-target="#myCarousel"></li>
                                    <!-- <li data-slide-to="1" data-target="#myCarousel"></li>
                                    <li data-slide-to="2" data-target="#myCarousel"></li>
                                    <li data-slide-to="3" data-target="#myCarousel"></li> -->
                                                                        <li class="" data-slide-to="4" data-target="#myCarousel"></li>
                                    <!-- <li data-slide-to="1" data-target="#myCarousel"></li>
                                    <li data-slide-to="2" data-target="#myCarousel"></li>
                                    <li data-slide-to="3" data-target="#myCarousel"></li> -->
                                                                    </ol><!-- Wrapper for slides -->
                                <div class="carousel-inner" role="listbox">
                                                                        <div class="item active">
                                        <a href="https://act.id/gempa-palu" title="" target="_blank">
                                            
                                            <img
                                                data-sizes="auto"
                                                class="lazyload optimumx"
                                                data-optimumx="2.5"
                                                src="https://act.id/themes/act_id/images/Wait.gif"
                                                data-srcset="https://act.id/upload/banner/Web-Banner-Gempa-Palu---1645x609_201810100841.jpg 175w,
                                                https://act.id/upload/banner/Web-Banner-Gempa-Palu---1645x609_201810100841.jpg 350w,
                                                https://act.id/upload/banner/Web-Banner-Gempa-Palu---1645x609_201810100841.jpg 525w,
                                                https://act.id/upload/banner/Web-Banner-Gempa-Palu---1645x609_201810100841.jpg 788w,
                                                https://act.id/upload/banner/Web-Banner-Gempa-Palu---1645x609_201810100841.jpg 1182w,
                                                https://act.id/upload/banner/Web-Banner-Gempa-Palu---1645x609_201810100841.jpg 1773w,
                                                https://act.id/upload/banner/Web-Banner-Gempa-Palu---1645x609_201810100841.jpg 2659w"
                                                alt="Donasi Gempa Palu Sigi Donggala" />

                                        </a>
                                    </div>
                                                                        <div class="item ">
                                        <a href="https://act.id/gempa-lombok" title="" target="_blank">
                                            
                                            <img
                                                data-sizes="auto"
                                                class="lazyload optimumx"
                                                data-optimumx="2.5"
                                                src="https://act.id/themes/act_id/images/Wait.gif"
                                                data-srcset="https://act.id/upload/banner/Web_Banner_IBL-01_201808310226.jpg 175w,
                                                https://act.id/upload/banner/Web_Banner_IBL-01_201808310226.jpg 350w,
                                                https://act.id/upload/banner/Web_Banner_IBL-01_201808310226.jpg 525w,
                                                https://act.id/upload/banner/Web_Banner_IBL-01_201808310226.jpg 788w,
                                                https://act.id/upload/banner/Web_Banner_IBL-01_201808310226.jpg 1182w,
                                                https://act.id/upload/banner/Web_Banner_IBL-01_201808310226.jpg 1773w,
                                                https://act.id/upload/banner/Web_Banner_IBL-01_201808310226.jpg 2659w"
                                                alt="Indonesia Bersama Lombok" />

                                        </a>
                                    </div>
                                                                        <div class="item ">
                                        <a href="https://act.id/program" title="" target="_blank">
                                            
                                            <img
                                                data-sizes="auto"
                                                class="lazyload optimumx"
                                                data-optimumx="2.5"
                                                src="https://act.id/themes/act_id/images/Wait.gif"
                                                data-srcset="https://act.id/upload/banner/Web_Banner_SKDI_Saatnya_Umat_Selamatkan_Umat-02_201807051055.jpg 175w,
                                                https://act.id/upload/banner/Web_Banner_SKDI_Saatnya_Umat_Selamatkan_Umat-02_201807051055.jpg 350w,
                                                https://act.id/upload/banner/Web_Banner_SKDI_Saatnya_Umat_Selamatkan_Umat-02_201807051055.jpg 525w,
                                                https://act.id/upload/banner/Web_Banner_SKDI_Saatnya_Umat_Selamatkan_Umat-02_201807051055.jpg 788w,
                                                https://act.id/upload/banner/Web_Banner_SKDI_Saatnya_Umat_Selamatkan_Umat-02_201807051055.jpg 1182w,
                                                https://act.id/upload/banner/Web_Banner_SKDI_Saatnya_Umat_Selamatkan_Umat-02_201807051055.jpg 1773w,
                                                https://act.id/upload/banner/Web_Banner_SKDI_Saatnya_Umat_Selamatkan_Umat-02_201807051055.jpg 2659w"
                                                alt="selamatkan umat" />

                                        </a>
                                    </div>
                                                                        <div class="item ">
                                        <a href="https://act.id/program/detail/savepalestine" title="" target="_blank">
                                            
                                            <img
                                                data-sizes="auto"
                                                class="lazyload optimumx"
                                                data-optimumx="2.5"
                                                src="https://act.id/themes/act_id/images/Wait.gif"
                                                data-srcset="https://act.id/upload/banner/Web_Banner_KK_Palestina-01_201806260852.jpg 175w,
                                                https://act.id/upload/banner/Web_Banner_KK_Palestina-01_201806260852.jpg 350w,
                                                https://act.id/upload/banner/Web_Banner_KK_Palestina-01_201806260852.jpg 525w,
                                                https://act.id/upload/banner/Web_Banner_KK_Palestina-01_201806260852.jpg 788w,
                                                https://act.id/upload/banner/Web_Banner_KK_Palestina-01_201806260852.jpg 1182w,
                                                https://act.id/upload/banner/Web_Banner_KK_Palestina-01_201806260852.jpg 1773w,
                                                https://act.id/upload/banner/Web_Banner_KK_Palestina-01_201806260852.jpg 2659w"
                                                alt="kapal kemanusiaan palestina" />

                                        </a>
                                    </div>
                                                                        <div class="item ">
                                        <a href="https://globalwakaf.com" title="" target="_blank">
                                            
                                            <img
                                                data-sizes="auto"
                                                class="lazyload optimumx"
                                                data-optimumx="2.5"
                                                src="https://act.id/themes/act_id/images/Wait.gif"
                                                data-srcset="https://act.id/upload/banner/Web_Banner_GW_Wakaf_Sumur_-_1645x609px-01_201806260909.jpg 175w,
                                                https://act.id/upload/banner/Web_Banner_GW_Wakaf_Sumur_-_1645x609px-01_201806260909.jpg 350w,
                                                https://act.id/upload/banner/Web_Banner_GW_Wakaf_Sumur_-_1645x609px-01_201806260909.jpg 525w,
                                                https://act.id/upload/banner/Web_Banner_GW_Wakaf_Sumur_-_1645x609px-01_201806260909.jpg 788w,
                                                https://act.id/upload/banner/Web_Banner_GW_Wakaf_Sumur_-_1645x609px-01_201806260909.jpg 1182w,
                                                https://act.id/upload/banner/Web_Banner_GW_Wakaf_Sumur_-_1645x609px-01_201806260909.jpg 1773w,
                                                https://act.id/upload/banner/Web_Banner_GW_Wakaf_Sumur_-_1645x609px-01_201806260909.jpg 2659w"
                                                alt="wakaf sumur" />

                                        </a>
                                    </div>
                                                                        <!-- <div class="item">
                                        <img alt="" src="images/resource/slider1.jpg">
                                    </div> -->
                                </div><!-- Left and right controls -->
                                <a class="left carousel-control" data-slide="prev" href="#myCarousel"
                                role="button"><span aria-hidden="true" class=
                                "glyphicon glyphicon-chevron-left"></span> <span class=
                                "sr-only">Previous</span></a> <a class="right carousel-control"
                                data-slide="next" href="#myCarousel" role="button"><span aria-hidden=
                                "true" class="glyphicon glyphicon-chevron-right"></span> <span class=
                                "sr-only">Next</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- Slider Section -->
     
       
 
            <div class="bottom-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7 column">
                            <div class="bottom-links">
                                <!-- <a href="#" itemprop="url" title="">Terms & Conditions</a> 
                                <a href="#" itemprop="url" title="">Privacy Policy</a>  -->
                                <a href="https://act.id/contact_us" itemprop="url" title="">Kontak Kami</a> 
                                 <!-- <a href="#" itemprop="url" title="">FAQ</a> -->
                             </div>
                        </div>
                        <div class="col-md-5 column">
                            <p><b>Copyright © 2017 ACT - All right reserved </b><br>ACT is audited by KAP Razikun & Tarko Sunaryo
                            <br>Registered Public Accountants a Member of MSI Global Alliance<br>Supported by Widjojanto, Sondhaji & Associates Law Firm
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src='https://act.id/themes/act_id/js/modernizr.custom.17475.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/jquery-2.1.4.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/bootstrap.min.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/bootstrap-datepicker.min.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/owl.carousel.min.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/jquery.poptrox.min.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/jquery.scrolly.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/jquery.knob.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/jquery.isotope.min.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/isotope-initialize.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/jquery.plugin.min.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/jquery.countdown.min.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/select2.min.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/loading.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/enscroll-0.5.2.min.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/layerslider/js/greensock.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/layerslider/js/layerslider.transitions.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/layerslider/js/layerslider.kreaturamedia.jquery.js' type='text/javascript'></script>
<script src='https://act.id/themes/act_id/js/form-validator/jquery.form-validator.min.js' type='text/javascript'></script>

    <script>
             jQuery(document).ready(function( $ ) {
                 /* ============ LAYER SLIDER ================*/
                 jQuery("#layerslider").layerSlider({
                     responsive: true,
                     responsiveUnder: 1280,
                     layersContainer: 1170,
                     skin: 'fullwidth',
                     hoverPrevNext: true,
                     skinsPath: 'layerslider/skins/'
                 });

                 /* ============ Sponsors Carousel ================*/
                 $('.sponsors-carousel').owlCarousel({
                     autoplay:true,
                     autoplayTimeout:2500,
                     smartSpeed:2000,
                     loop:true,
                     dots:false,
                     nav:true,
                     margin:10,
                     mouseDrag:true,
                     items:5,
                     autoHeight:true,
                     responsive : {
                         0 : {items : 1},
                         480 : {items :2},
                         768 : {items : 3},
                         1200 : {items : 5},
                     }   
                 }); 

                 /* ============ Single Person Donate Carousel ================*/
                 $('.single-donate-car').owlCarousel({
                     autoplay:true,
                     autoplayTimeout:2500,
                     smartSpeed:2000,
                     loop:false,
                     dots:false,
                     nav:true,
                     margin:0,
                     mouseDrag:true,
                     items:1,
                     autoHeight:true 
                 });     

             });  
    </script> 
    <script>
             jQuery(document).ready(function( $ ) {
                 /* ============ LAYER SLIDER ================*/
                 jQuery("#layerslislider").layerSlider({
                     responsive: true,
                     responsiveUnder: 1280,
                     layersContainer: 1170,
                     skin: 'fullwidth',
                     hoverPrevNext: true,
                     skinsPath: 'layerslider/skins/'
                 });
             

                 /* ============ Welfare Projects Carousel ================*/
                 $('.welfare-projects-carousel').owlCarousel({
                     autoplay:true,
                     autoplayTimeout:2500,
                     smartSpeed:2000,
                     autoplayHoverPause:true,
                     loop:true,
                     dots:false,
                     nav:false,
                     margin:0,
                     mouseDrag:true,
                     items:4,
                     autoHeight:true,
                     responsive : {
                         0 : {items : 1},
                         480 : {items :2},
                         768 : {items : 3},
                         1200 : {items : 4},
                     }   
                 });  


                 /* ============ Sponsors Carousel ================*/
                 $('.sponsors-carousel').owlCarousel({
                     autoplay:true,
                     autoplayTimeout:2500,
                     smartSpeed:2000,
                     loop:true,
                     dots:false,
                     nav:true,
                     margin:10,
                     mouseDrag:true,
                     items:5,
                     autoHeight:true,
                     responsive : {
                         0 : {items : 1},
                         480 : {items :2},
                         768 : {items : 3},
                         1200 : {items : 5},
                     }   
                 });  




                 /* ============ Count Down Timer ================*/
                 $(function () {
                     var date = new Date();
                     date = new Date(2017, 4 - 1, 12);
                     $('.count-down').countdown({until: date});
                 });
                 $(function () {
                     var date2 = new Date();
                     date2 = new Date(2016, 4 - 1, 12);
                     $('.count-down2').countdown({until: date2});
                 });  

             });  
    </script> 
    <script>
             jQuery(document).ready(function( $ ) {
            var myElem = document.getElementById('deal-selector');
            if (myElem === null){}
            else{
                 $('.deal-selector').slick({
                   infinite: true,
                   slidesToShow: 2,
                   slidesToScroll:1,
                   vertical:true,
                   autoplay:true,
                   arrows:false,
                   focusOnSelect: true,
                   draggable:false,
                   asNavFor: '.deal-detail-carousel'
                 });     
                 $('.deal-detail-carousel').slick({
                   infinite: true,
                   autoplay:true,
                   slidesToShow: 1,
                   slidesToScroll:1,
                   arrows:false,
                   asNavFor: '.deal-selector'
                 });     


                 /* ============ Count Down Timer ================*/
                 $(function () {
                     var date = new Date();
                     date = new Date(2016, 5 - 1, 16);
                     $('.count-down1').countdown({until: date});
                 });
                 $(function () {
                     var date = new Date();
                     date = new Date(2017, 4 - 1, 12);
                     $('.count-down2').countdown({until: date});
                 });
                 $(function () {
                     var date = new Date();
                     date = new Date(2017, 12 - 1, 25);
                     $('.count-down3').countdown({until: date});
                 });
                 $(function () {
                     var date = new Date();
                     date = new Date(2017, 12 - 1, 25);
                     $('.count-down4').countdown({until: date});
                 });

                 /* ============ Sponsors Carousel ================*/
                 $('.sponsors-carousel').owlCarousel({
                     autoplay:true,
                     autoplayTimeout:2500,
                     smartSpeed:2000,
                     loop:true,
                     dots:false,
                     nav:true,
                     margin:10,
                     mouseDrag:true,
                     items:5,
                     autoHeight:true,
                     responsive : {
                         0 : {items : 1},
                         480 : {items :2},
                         768 : {items : 3},
                         1200 : {items : 5},
                     }   
                 }); 
            }                


                 /*=================== Toggle Header ===================*/ 
                 (function() {
                 var toggles = document.querySelectorAll(".c-hamburger");
                 for (var i = toggles.length - 1; i >= 0; i--) {
                   var toggle = toggles[i];
                   toggleHandler(toggle);
                 };
                 function toggleHandler(toggle) {
                   toggle.addEventListener( "click", function(e) {
                     e.preventDefault();
                     (this.classList.contains("is-active") === true) ? this.classList.remove("is-active") : this.classList.add("is-active");
                   });
                 }

                 })();

                 /* ============ Causes Carousel ================*/
                 $('.causes-carousel').owlCarousel({
                     autoplay:true,
                     autoplayTimeout:2500,
                     smartSpeed:2000,
                     loop:false,
                     dots:false,
                     nav:false,
                     margin:0,
                     mouseDrag:true,
                     items:2,
                     autoHeight:true,
                     responsive : {
                         0 : {items : 1},
                         480 : {items :1},
                         768 : {items : 2},
                         1200 : {items : 2},
                     }   
                 });  

             });  
    </script>
    <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58ac008aec741d001187f30b&product=inline-share-buttons"></script>
    <script src="https://act.id/themes/act_id/js/script.js"> 
    </script>
    <script>
      $.validate({
        modules : 'toggleDisabled',
        disabledFormFilter : 'form.toggle-disabled',
      });
    </script>
    <script type="text/javascript">
        $(function () {
            $('#datepicker1').datepicker();
            $('#datepicker2').datepicker();
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function(){
            var code = "id";
            var lang = {'id':'INDONESIA','en':'ENGLISH','ar':'ARABIC'};
            // alert(code);
            $("#lang").html(lang[code]+' <span class="caret"></span>');
        });
    </script>


    <!-- Tambahan Ishak Lazy Load Image-->
<script src="https://afarkas.github.io/respimage/respimage.min.js"></script>
<script>
    window.lazySizesConfig = window.lazySizesConfig || {};
    window.lazySizesConfig.loadMode = 1;
</script>
<script src="https://act.id/themes/act_id/js/lazysizes.min.js"></script>
<script src="https://act.id/themes/act_id/js/ls.optimumx.min.js"></script>
<script>

    (function(){

        var dpr = (window.devicePixelRatio || 1);
        var max = params.optimumx || 'image specific optimum';
        var calcDpr = Math.min(dpr, max) || params.optimumx == 'auto' ? 'what the default <code>getOptimumX</code></code> callback returns' : 'image specific';
        $('<div class="alert alert-info"><p>Your device has a pixel ratio of '+ dpr +', ' +
        'while <code>data-optimumx="'+ max +'"</code> is set.</p>' +
        '<p>This means images should be around a pixel density of "'+ calcDpr +'".</p></div>')
                .insertAfter('.alert-legend');

        $('body').before('<strong class="label label-default label-config">Used optimumx option: '+max+'</strong>');

    })();
    (function(){
        var timer;
        var _ = window.respimage._;
        var dpr = _.DPR;
        var showdpr = function(){
            var beforeCandidate, afterCandidate, curCandidate, can, curRes, size;
            var info = '<div class="dpr-info">';
            var img = this;
            var imgData = this._demoSrcset;
            var curSrc = this.currentSrc || this.src;

            if(!imgData || !curSrc){return;}
            beforeCandidate = '<strong class="label label-default">--</strong>';
            afterCandidate = '<strong class="label label-danger">--</strong>';
            curCandidate = '<strong class="label label-success">--</strong>';
            size = '';

            for(var i = 0; i < imgData.cands.length; i++){
                can = imgData.cands[i];
                if(can.url == curSrc){
                    curRes = Math.floor((can.w / this.offsetWidth) * 1000) / 1000;

                    curCandidate = '<strong class="label label-success">'+ curRes +'x</strong>';
                    can = imgData.cands[i - 1];
                    if(can){
                        beforeCandidate = '<strong class="label label-default">'+ (Math.floor((can.w / this.offsetWidth) * 1000) / 1000) +'x</strong>';
                    }
                    can = imgData.cands[i + 1];
                    if(can){
                        afterCandidate = '<strong class="label label-danger">'+ (Math.floor((can.w / this.offsetWidth) * 1000) / 1000) +'x</strong>';
                    }

                    size = '<br /><strong class="label label-danger">Estimated file size: '+ Math.round(this.offsetWidth * this.offsetHeight * Math.pow(curRes, 2) / 1500) +'kb</strong>';
                    break;
                }
            }

            info += beforeCandidate +' '+ curCandidate +' ' + afterCandidate + size;

            info += '</div>';
            $(img)
                    .parent()
                    .find('.dpr-info')
                    .remove()
                    .end()
                    .append(info)
            ;
        };

        var showDprs = function(){
            $('img').each(showdpr);
        };
        var tShowDprs = function(){
            clearTimeout(timer);
            timer = setTimeout(showDprs, 300);
        };
        document.addEventListener('load', tShowDprs, true);
        window.addEventListener('resize', tShowDprs);
    })();
</script>
<!-- Akhir Tambahan Ishak Lazy Load Image --> 
</body>
</html>